FROM node:14-slim

WORKDIR /app

# RUN npm init -y
# RUN npm install --save-dev cross-env laravel-mix ts-loader typescript vue-template-compiler
# RUN npm install browser-sync browser-sync-webpack-plugin vue